### ISSUE TITLE
Port to Python3

### ISSUE THREAD

**Issue by Ovalelephant35** [sugarlabs/panorama#13]
Unable to run in latest sugar environment.

**Comment by kshitijdshah99** [comment]
@Ovalelephant35 can I work on this issue?

**Comment by kshitijdshah99** [comment]
@Ovalelephant35 @quozl I have port all necessary files to Python 3 kindly review my PR #14 and let me know if any changes.

**Comment by Ovalelephant35** [comment]
I can only suggest you to mention this issue in your pr as closes and write a little description, rest @quozl / other devs will see.
Thankyou.

**Comment by quozl** [comment]
Keeping others informed; a previous pull request was almost complete, but two more pull requests were made.  The oldest was merged today.  That closes the issue.  However, there's no reason why the two new pull requests _don't_ contain something extra that is needed, so will let them remain open until the authors are happy.
